[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "yadinassi"
dynamic = ["version"]
description = "An extensible interpreter for a subset of the 1C BSL language"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = ["prompt-toolkit==3.0.53"]

[project.optional-dependencies]
build = ["pyinstaller==6.22.2"]

[project.scripts]
yadinassi = "yadinassi.cli:main"

[tool.setuptools.packages.find]
include = ["yadinassi*"]

[tool.setuptools.dynamic]
version = {attr = "yadinassi.__version__"}
